### ISSUE TITLE
Xamarin Xcode beta releases

### ISSUE THREAD

**Issue by SamuelDebruyn** [bitrise-io/osx-box-bootstrap#105]
It's awesome that you provide stacks with the Xcode beta versions (which is now at Xcode 10 GM), but the Xamarin developers are missing out.

Xamarin provides preview releases a couple of hours/days after each Xcode beta release. The latest one is also for Xcode 10 GM. https://releases.xamarin.com/preview-release-xcode-10-gm/

It would be very useful to have a Xamarin beta stack which points to these 2 previews.

I'd say that stack should also include the latest stable Android version so that a single stack can build apps for both platforms, but this could be open for discussion.

**Comment by bitce** [comment]
Hi there!

Thanks for contacting us about this!

We wouldn't want Xamarin developers to feel left out of course. Truth is that we do require internal testing of these VMs before releasing them, and it's just hard to manage everything all at once.

That said, the preview release seems to be entirely compatible with our VS4Mac, so we are looking into this as we speak. If everything goes smoothly you can expect this to be available starting from next week!

I'll make sure to let you know here if we have an update on the matter 🙂

**Comment by bitce** [comment]
Just an update: A beta stack should be available from tomorrow and the stable version should follow early next week!

**Comment by viktorbenei** [comment]
Closing (it's been addressed but never closed).
