### ISSUE TITLE
Use ramdisk for Xcode derived data and cache

### ISSUE THREAD

**Issue by dagio** [bitrise-io/osx-box-bootstrap#19]
Have you try the following script or similar way to improve build time ?

https://gist.github.com/derjohng/a828e4c40a328fe5881f

**Comment by viktorbenei** [comment]
Hmm.. interesting idea. We didn't try it yet.

**Comment by dagio** [comment]
I will close the issue. This can lead to build fail because the ramdisk can easily get full.

**Comment by viktorbenei** [comment]
All right, thank you!
