### ISSUE TITLE
Xcode Edge stack installs previous macOS version

### ISSUE THREAD

**Issue by arielelkin** [bitrise-io/osx-box-bootstrap#229]
Currently the Xcode Edge stack is providing macOS 10.14.6 Mojave even though macOS 10.15 Catalina was released six months ago.

**Comment by fehersanyi-bitrise** [comment]
Hello @arielelkin the reason for this is that macOS Catalina is still beta. On the Xcode Edge stack we have the latest stable tools. :) 
As you can read in the stack description: `This Edge stack includes the latest stable Xcode version. Exact macOS version is the same as on that stack. `

**Comment by arielelkin** [comment]
@fehersanyi-bitrise I beg to differ... If you visit https://www.apple.com/macos you'll be redirected to the latest release version of macOS, which happens to be Catalina

**Comment by arielelkin** [comment]
further proof is that [Catalina is on the App Store ](https://apps.apple.com/gb/app/macos-catalina/id1466841314?mt=12) and Apple doesn't release beta software on the app store

**Comment by fehersanyi-bitrise** [comment]
Sorry @annabatki that is my mistake I take it, 10.15.4 is in beta, .3 is already stable. But then again, the Xcode edge will be updated to have Catalina when the Xcode 11.4 GE comes out. :)

**Comment by arielelkin** [comment]
> The Xcode edge will be updated to have Catalina when the Xcode 11.4 GM comes out

According to [your definition of Xcode Stacks](https://devcenter.bitrise.io/infrastructure/stack-update-and-removal-policy/#xcode-stacks), the Xcode Edge stack is expected to have the latest stable macOS... We need Catalina because some features of iOS 13 don't run in the iOS Simulator in Mojave.

**Comment by fehersanyi-bitrise** [comment]
@arielelkin this is in the edge stacks description:
`This Edge stack includes the latest stable Xcode version. Exact macOS version is the same as on that stack.` 
The latest stable Xcode is 11.3.x that runs with Mojave on our Build machines.
If you really need the capabilities of Catalina, I can recommend using the 11.4.x stack for the time being. :)

**Comment by arielelkin** [comment]
It's unfortunate you don't offer a stack with the latest stable releases of macOS and Xcode.
