### ISSUE TITLE
OSX stack with newest stable Flutter possible?

### ISSUE THREAD

**Issue by mark-veenstra** [bitrise-io/osx-box-bootstrap#246]
Hi,

Would it be possible to have a stack with the latest flutter stable? This would speed up our builds since we need to upgrade flutter first every build.

Current version installed version in the stack: `1.12.13+hotfix.8` \
Current latest stable version: `Flutter 1.17.1 • channel stable`

Thanks in advance.

Mark

**Comment by lmesz-bitrise** [comment]
Hey Mark,

Thanks for the heads-up, very good point.
We will do the update and it will be going to the wild with the next weekly release.

Thank you again
Laci

**Comment by lmesz-bitrise** [comment]
Hey again,

As you can see in the announcement of the weekly update https://discuss.bitrise.io/t/weekly-virtual-machine-stack-updates-2020-may-23/13064
We updated the stack which now built with Flutter version 1.17.1 in it.

Thank you for the advice and happy building!
Laci
