### ISSUE TITLE
Adding applesimutils to the stack

### ISSUE THREAD

**Issue by mark-veenstra** [bitrise-io/osx-box-bootstrap#251]
Hi,

To be able to run E2E test with `flutter drive` we are in need of `applesimutils` to be added to the stack. With `applesimutils` we could allow native persmission that are needed with the Flutter tests.

See:
* https://github.com/flutter/flutter/issues/12561#issuecomment-507484574
* https://github.com/wix/AppleSimulatorUtils

Thanks

**Comment by bitrisekristof** [comment]
Hey,

Thanks for the advice! We are installing it. I hope it will go out with the net after weekly update (June 6.).

Thanks

**Comment by Kanan-Bitrise** [comment]
Hey Mark, 

Applesimutils will be available tomorrow with the weekly update.

Thanks for the suggestion :)

**Comment by peterheja-bitrise** [comment]
Applesimutils was added to the stacks.
https://github.com/bitrise-io/osx-box-bootstrap/pull/253
