### ISSUE TITLE
Question: create React Native box or update Xamarin?

### ISSUE THREAD

**Issue by Minishlink** [bitrise-io/osx-box-bootstrap#34]
Hi,

I would like to propose a PR for preinstalling React Native tools. Should I create a `react-native-playbook.yml`, or do you feel it's best to rename the Xamarin box to something like Cross-platform box and update this one?

**Comment by viktorbenei** [comment]
That's a great question @Minishlink !

We will most likely create a "cross platform" stack in the near future, specifically for tools like RN which can build both iOS and Android, but we're not sure yet whether this should be done in a single build / on a single stack or in separate ones, something like this: https://discuss.bitrise.io/t/seperate-stacks-for-seperate-workflows-trigger-multiple-workflows-builds-at-the-same-time-parallel-builds/410

**Comment by viktorbenei** [comment]
In any case, I'd suggest to bring this question up at https://discuss.bitrise.io - as that's our primary discussion platform, tracked by all of our devs ;)

**Comment by Minishlink** [comment]
Cool, thanks! I brought the topic up here: https://discuss.bitrise.io/t/create-react-native-box/509

**Comment by viktorbenei** [comment]
I think most of the required tools are now available and the Xamarin stack should be suitable for RN projects, so closing this here, comments are still welcome on discuss (https://discuss.bitrise.io/t/create-react-native-box/509)

Thanks for the infos @Minishlink ! :)
