### ISSUE TITLE
fbsimctl: No such file or directory

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/osx-box-bootstrap#38]
Thoughts on preinstalling fbsimctl on the edge stack?

```
brew tap facebook/fb
brew install fbsimctl --HEAD
```

- https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl

The code isn't stable & compatibility varies greatly depending on Xcode version. However it's one of the few ways to get accurate video recordings from iOS simulators.

**Comment by viktorbenei** [comment]
We're not against preinstalling it, but if it's not stable yet or have to be updated frequently, I'm not sure if that's the best way to do it. But it's up to you, if you think that a preinstalled version today would work in the future too / there's no risk in preinstalling it, we're open to accept it.

Related: did you try LinkedIn's https://github.com/linkedin/bluepill ? It seems there's quite a bit of overlap, we heard great things about bluepill but we don't have any stats about how reliable it is or how much faster it is.

There are a couple of other options discussed here too: https://discuss.bitrise.io/t/allow-xcode-testing-step-for-multiple-devices-operating-systems/147/3

**Comment by viktorbenei** [comment]
There are so many iOS unit testing tools aiming for more reliable or faster execution - I wonder if maybe we should start a thread for this on discuss.bitrise.io - WDYT @bootstraponline ?
Might help to share options there, with setup steps/configs etc.

**Comment by bootstraponline** [comment]
> if you think that a preinstalled version today would work in the future too

I don't think it'll work in the future since it's not stable and new Xcode releases often break it entirely.

> Related: did you try LinkedIn's https://github.com/linkedin/bluepill ?

I haven't tried that yet. They support EarlGrey so it's definitely on my list to checkout someday.

> I wonder if maybe we should start a thread for this on discuss.bitrise.io - WDYT @bootstraponline ?

I think [this thread](https://discuss.bitrise.io/t/ios-automated-test-durations-multiple-targets/550) is already addressing the topic. In my experience, one of the best ways to increase iOS UI testing stability is to upgrade the underlying hardware.

I'll close this since it sounds like unstable/frequently changing software isn't a good fit for preinstalling.
