### ISSUE TITLE
Support Docker

### ISSUE THREAD

**Issue by caiofbpa** [bitrise-io/osx-box-bootstrap#40]
Any reason Docker is supported in the Linux boxes but not on the macOS boxes?

It would be really nice if I could get docker working on my Xamarin Stable stack, so I can quickly setup a disposable backend for my app, for testing purposes.

**Comment by viktorbenei** [comment]
Closing as "duplicate" - related discussion: https://discuss.bitrise.io/t/how-to-use-your-own-docker-image-for-your-builds/69/3
