### ISSUE TITLE
pre install danger-swift

### ISSUE THREAD

**Issue by chosa91** [bitrise-io/osx-box-bootstrap#449]
Having [danger-swift](https://github.com/danger/swift#setup) pre-installed would speed up our workflows radically

```
brew install danger/tap/danger-swift
```

**Comment by Roland-Bak** [comment]
Hi there @chosa91 👋 

If you'd like danger-swift to be pre-installed, you can create a Pull Request, adding your changes to the playbook.yml (Ansible playbook) of this repository. Please also add a related test/report to the system_report.sh file, which is used to test & list the pre-installed tools. 🙂
