### ISSUE TITLE
Question: It is possible to build with a specific version of Xamarin.IOS

### ISSUE THREAD

**Issue by xiz0r** [bitrise-io/osx-box-bootstrap#46]
Hi,
I need to compile my project with Xamarin.IOS version 10.6.
It is posible?
thanks

**Comment by viktorbenei** [comment]
Hi,

You can find the system reports at: https://github.com/bitrise-io/bitrise.io/tree/master/system_reports

Xamarin.iOS seems to be really ancient, even our almost year old LTS stack which has the oldest Xamarin.iOS version is at 9.8.2.22 (https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xamarin-stable-LTS.log#L466)
And the current "Stable" is at 10.8.0.175 (https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xamarin-stable.log#L545)

**Comment by viktorbenei** [comment]
Edited my reply, sorry, I misread your original comment.
