### ISSUE TITLE
Playbook not compatible with java 9

### ISSUE THREAD

**Issue by koral--** [bitrise-io/osx-box-bootstrap#55]
Follow-up of https://github.com/bitrise-io/osx-box-bootstrap/pull/50#issuecomment-331746592
`java` cask has been updated to 9 and `jce-unlimited-strength-policy` cask is being moved to caskroom/versions tap: https://github.com/caskroom/homebrew-cask/issues/38574
It seems that playbook needs to be updated.

**Comment by ghaabor** [comment]
Thanks for reporting this @koral--! I'll remove the `jce-unlimited-strength-policy` cask since my understanding is that in Java 9 it's a built-in option (https://stackoverflow.com/a/42163925) and the playbook will install Java 9 on all newly built macOS images.

**Comment by koral--** [comment]
Exactly. JCE is no longer needed and java 9 will be installed now by default.
Some things (steps or users' workflows) may not be compatible with java 9, but it is out of the scope of this issue.

**Comment by viktorbenei** [comment]
Thanks @koral-- ! :)
