### ISSUE TITLE
CocoaPods version 1.10.1 too old for Firebase 8.8.0 in all your stacks

### ISSUE THREAD

**Issue by carelliguillaume** [bitrise-io/osx-box-bootstrap#550]
We want to use Firebase iOS Pod version 8.8.0 but it needs at least CocoaPods version 1.10.2, and in all your Bitrise Stacks, its CocoaPods 1.10.1.

Is there a way to update CocoaPods in the existing stacks or is it possible to create a new stack for it ?

You can see the corresponding error in our pipeline :
https://app.bitrise.io/build/c81ec993-098f-4f08-a581-19e50f65aa4d#?tab=log

[error] Analyzing dependencies 
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/` 
CocoaPods 1.11.2 is available. 
To update use: `gem install cocoapods` 
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2 
[!] `GoogleAppMeasurement` requires CocoaPods version `>= 1.10.2`, which is not satisfied by your current version, `1.10.1`. 
[ERROR] An error occurred while running subprocess capacitor. 

capacitor sync ios exited with exit code 1. 

Re-running this command with the --verbose flag may provide more information. 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! ulys-nav@0.0.1 ci:ios: `npm run ios:google && npm run ios:applinks && npm run ios:info-plist && ionic capacitor sync ios --no-build --configuration production` 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the ulys-nav@0.0.1 ci:ios script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
npm ERR! A complete log of this run can be found in: 
npm ERR! /Users/vagrant/.npm/_logs/2021-09-29T09_04_59_183Z-debug.log 
Error running command run ci:ios: exit status 1

**Comment by sturman** [comment]
This issue might be fixed after #555 is merged
